#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill $HOME/Imagens/21.jpg &
$HOME/.config/polybar/launch.sh &

picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V

bspc config border_width         1.5
bspc config window_gap          8

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a google-chrome-stable desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a code desktop='^3'
